### PR TITLE
Added Feature to Prevent Walking Into the Portal After Death

### PR DESCRIPTION
**Pull request by HighCrit**
**What's new:**
Added an option to prevent the player from walking into the portal straight after dying. To resume movement, the user has to re-press the desired direction of movement. This feature can be disabled through the settings menu.

**Possible issues:**
If a non named "You" were to die in your server it would trigger this system. However, the user "You" has MVP and has not been online for over a year. Therefore this issue can be disregarded.

### CODE REVIEW

**Comment by biscuut** [comment]
I mean i've never really had this happen to me but sure, since you spent so much time on it 😂

**Comment by HighCrit** [comment]
I hadn't had this happen. Until I started fishing at the barn. Where it feels like the spawn is on the warp pad.

**Comment by HighCrit** [comment]
I could make an AT to unpress the backwards and strafe keys. So the user could continue walking forward, jumping and swinging their sword. If that's more desirable. However, it would mean this mod classifies as a core mod.

**Comment by biscuut** [comment]
Thank you :D

**Pull request merged**
