### PR TITLE
Add new Organize Enchantments feature

### PR DESCRIPTION
**Pull request by orchidalloy**
This PR fully implements a new feature listed as _Organize Long Enchantment Lists_

While turned on, the tooltips of items with 6 or more enchantments are modified like this:
- The enchantments are sorted by type and importance: Essential/damage enchantments first, utility enchantments after, etc.
- Detrimental sword enchantments are put at the top to be easily seen (smite, bane, knockback, fire, venom). Similarly, Cleave and Thunderlord are [not detrimental but still up to user preference](https://hypixel.net/threads/guide-in-defense-of-cleave-and-thunderlord.2317978/) and can be easily noticed at the bottom.
- There will be 2 enchantments per row by default
- A sword or book with 15 or more enchantments will show 3 enchantments per row

There are several purposes/benefits:
- Allow the user to take a quick glance at any item they come across and get a good idea of its enchantments
- Provide a more satisfactory display of enchantments compared to the game's bland alphabetical order
- Reduce the vertical space used

Performance was a consideration while writing the code. It's probably not the most efficient approach though.
I've tested the changes in-game by looking at many items from auction and so far it's worked great.

Here are some images too
[Toggle box in the settings](https://media.discordapp.net/attachments/624271962142933012/624423087072477204/unknown.png)
[Example sword](https://media.discordapp.net/attachments/624271962142933012/624423280962568215/unknown.png?width=329&height=481)
[Example bow](https://media.discordapp.net/attachments/624271962142933012/624423478589784084/unknown.png)
[Example rod](https://media.discordapp.net/attachments/624271962142933012/624423627047174175/unknown.png)
[Example book](https://media.discordapp.net/attachments/624271962142933012/624423960557387845/unknown.png)

### CODE REVIEW

**Comment by DaPigGuy** [comment]
This would be a bit more work, but instead of hardcoded priorities for enchantments, you could instead make it configurable.

**Comment by orchidalloy** [comment]
I think a separate config file for the list would fit. I don't think it makes sense nor would it be worth the effort to make a custom GUI for it.

**Comment by orchidalloy** [comment]
Hey, I just pushed a commit that fixes a bug on Hypixel Skyblock where Respiration, Depth Strider and Aqua Affinity would appear at the top of an item's tooltip for no reason.
I just put it into this branch because it fits. It's not a toggleable feature because simple bugfixes like these really aren't subjective.

**Comment by biscuut** [comment]
ok thanks orchid ill be checking it out

**Comment by orchidalloy** [comment]
please merge soon, I made the mistake of making these changes in my master branch lmao

**Comment by orchidalloy** [comment]
Replaced by #143

**Pull request closed without merging**
